name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-13-xl

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: make
      
    - uses: actions/upload-artifact@v3
      with:
        name: AppCommander IPA
        path: AppCommander.ipa
